cluster/gce: add NODE_NVDIMM
There are alpha machine types that have non-volatile DIMMs, aka
persistent memory (PMEM). The new NODE_NVDIMM variable can be used
to enable that hardware feature. A suitable machine type must
be selected separately.

This is work-in-progress. It currently fails like this because the
usage of the instance template with that alpha features fails with an
internal error:

gcloud compute instance-groups managed create kubernetes-minion-group ... --base-instance-name kubernetes-minion-group --size 3 --template kubernetes-minion-template
ERROR: (gcloud.compute.instance-groups.managed.create) Could not fetch resource:
 - Internal error. Please try again or contact Google Support. (Code: '58EE3BE001DE4.A989D8E.AB0DD3DA')